language: node_js
node_js:
    - '10'
cache:
    directories:
        - node_modules
jobs:
    include:
          before_script: npm install --ignore-scripts
        - stage: Test
          script: npm t
