os: linux
dist: trusty
language: node_js
node_js:
    - '10'
cache:
    directories:
        - node_modules

install: npm install --ignore-scripts

script:
    - npm t
    - npm run build

before_deploy:
    - echo "@mjefi:registry=https://npm.pkg.github.com/" > "$HOME/.npmrc"
    - echo "//npm.pkg.github.com/:_authToken=${GITHUB_TOKEN}" > "$HOME/.npmrc"
deploy:
    provider: script
    script: npm run publish
    skip_cleanup: true
    on:
        branch: master
