language: node_js
node_js:
    - '10'
cache:
    directories:
        - node_modules
jobs:
    include:
          before_script: npm i
        - stage: Test
          script: npm t
        - stage: Build Packages
          before_script: npm run build
          script: git status
        - stage: Version Packages
          before_script: changeset status
          script: npx changeset version
        - stage: Release
          before_deploy: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > "$HOME/.npmrc"
          deploy:
              provider: script
              script: npm run publish
              skip_cleanup: true
              on:
                  tags: true
                  branch: master
